# Generated by Django 4.0.1 on 2022-01-25 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs_user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2022, 1, 25, 11, 42, 54, 174196, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affairs_user',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 1, 25, 11, 44, 32, 599457, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
